# Generated by Django 4.2.18 on 2025-02-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='t',
        ),
    ]
