services:
   django:
      hostname: django
      build: .
      entrypoint: ["tail", "-f", "/dev/null"]
      # entrypoint:
      #    ["python3", "coursesProject/manage.py", "runserver", "0.0.0.0:8000"]
      volumes:
         - ./code:/code
      ports:
         - 8000:8000
