# Generated by Django 4.2.16 on 2024-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_date_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
