# Generated by Django 4.2.18 on 2025-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_novellservicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novellservicemodel',
            name='sign_on',
            field=models.CharField(max_length=20),
        ),
    ]
