# Generated by Django 4.2.18 on 2025-01-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
