# Generated by Django 4.2.19 on 2025-02-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('img', models.ImageField(upload_to='public/media')),
                ('messure', models.IntegerField(choices=[(0, 'Units'), (1, 'Liters')], default=0)),
            ],
        ),
    ]
