# Generated by Django 4.2.19 on 2025-02-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='img',
            field=models.ImageField(upload_to='resources'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantity', models.PositiveIntegerField()),
                ('id_craft_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_crafted_resource', to='objects.resource')),
                ('id_needed_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_needed_resource', to='objects.resource')),
            ],
        ),
    ]
