# Generated by Django 4.2.19 on 2025-02-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_resource_img_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuantity',
            field=models.FloatField(),
        ),
    ]
