# Generated by Django 4.2.19 on 2025-02-28 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999), django.core.validators.DecimalValidator(decimal_places=3, max_digits=6)]),
        ),
    ]
