# Generated by Django 4.2.18 on 2025-01-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_alter_book_slug_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fkbooks', to='books.author'),
        ),
    ]
