# Generated by Django 4.2.16 on 2024-11-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tittle',
            field=models.CharField(max_length=200),
        ),
    ]
