# Generated by Django 4.2.16 on 2024-11-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_url_alter_blog_fecha_alter_blog_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tittle',
            new_name='title',
        ),
    ]
