# Generated by Django 4.2.16 on 2024-11-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='models/blogs/img')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
