# Generated by Django 4.2.19 on 2025-02-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
