# Generated by Django 4.2.16 on 2024-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_generator_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
