# Generated by Django 4.2.16 on 2024-11-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_resource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(upload_to='img/calculator/resources'),
        ),
    ]
