# Generated by Django 4.2.16 on 2024-11-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_resource_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ticks',
            new_name='segundos',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primaryResource1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_1', to='calculator.resource'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primaryResource2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_2', to='calculator.resource'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primaryResource3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_3', to='calculator.resource'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primaryResource4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_4', to='calculator.resource'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='udsResource2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='udsResource3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='udsResource4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
