# Generated by Django 4.2.16 on 2024-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='img',
            field=models.ImageField(default='/code/satisfactory_calculator/media/img/', height_field=250, upload_to='img/', width_field=200),
            preserve_default=False,
        ),
    ]
