# Generated by Django 4.2.16 on 2024-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_generator_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='img',
            field=models.ImageField(upload_to='img/calculator'),
        ),
    ]
