# Generated by Django 4.2.16 on 2024-11-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_generator_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uds', models.SmallIntegerField()),
                ('udsResource1', models.SmallIntegerField()),
                ('udsResource2', models.SmallIntegerField(blank=True)),
                ('udsResource3', models.SmallIntegerField(blank=True)),
                ('udsResource4', models.SmallIntegerField(blank=True)),
                ('ticks', models.SmallIntegerField()),
                ('primaryResource1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_1', to='calculator.resource')),
                ('primaryResource2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_2', to='calculator.resource')),
                ('primaryResource3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_3', to='calculator.resource')),
                ('primaryResource4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Material_4', to='calculator.resource')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resultado', to='calculator.resource')),
            ],
        ),
    ]
