# Generated by Django 4.2.16 on 2024-11-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_resource_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='media/img/', height_field='150px', upload_to='img/calculator/resources', width_field='150px'),
            preserve_default=False,
        ),
    ]
