# Generated by Django 4.2.16 on 2024-11-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_rename_ticks_recipe_segundos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='segundos',
            new_name='ticks',
        ),
    ]
